version: '3.8'

services:
  jenkins-master:
    build:
      context: ./jenkins-master
      dockerfile: Dockerfile
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins-master/ssh:/var/jenkins_home/.ssh
    networks:
      - jenkins-net

  jenkins-agent1:
    build:
      context: ./jenkins-agent
      dockerfile: Dockerfile
    container_name: jenkins-agent1
    volumes:
      - ./jenkins-agent/ssh:/home/jenkins/.ssh
    networks:
      - jenkins-net

  jenkins-agent2:
    build:
      context: ./jenkins-agent
      dockerfile: Dockerfile
    container_name: jenkins-agent2
    volumes:
      - ./jenkins-agent/ssh:/home/jenkins/.ssh
    networks:
      - jenkins-net

  nginx-web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-web
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssh:/root/.ssh
      - web_content:/usr/share/nginx/html
    networks:
      - jenkins-net

networks:
  jenkins-net:
    driver: bridge

volumes:
  jenkins_home:
  web_content: